# Generated by Django 2.2.7 on 2020-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200114_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Standard', 'Standard'), ('Advanced', 'Advanced')], default='Standard', max_length=10),
        ),
    ]
