# Generated by Django 2.2.7 on 2020-01-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Standard', 'Standard'), ('Advanced', 'Advanced'), ('All', 'ImmediateStandardAdvanced')], default='All', max_length=10),
        ),
    ]
