# Generated by Django 2.2.7 on 2020-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20200114_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avail',
            field=models.CharField(choices=[('Always', 'Always')], default='Always', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Standard', 'Standard'), ('Advanced', 'Advanced')], default='Standard', max_length=10),
        ),
    ]
