# Generated by Django 2.2.7 on 2020-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20200114_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avail',
            field=models.CharField(choices=[('Always', 'Always'), ('Not', 'Not')], default='Always', max_length=10),
        ),
    ]
