# Generated by Django 2.2.7 on 2020-01-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20200114_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avail',
        ),
    ]
