# Generated by Django 2.2.7 on 2020-01-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_product_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Advanced_availabilty',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Immediate_availability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Standard_availability',
            field=models.BooleanField(null=True),
        ),
    ]
