# Generated by Django 3.0.2 on 2020-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200106_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
