# Generated by Django 3.0.2 on 2020-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200106_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
